baseURL= "https://CatarinaSeigward.github.io/"
languageCode = "en-us"
title = "Kaiwen Lin"
theme = "personal-web"
copyright="Â© Kaiwen Lin"
googleAnalytics = ""

[services]
  [services.disqus]
    shortname = "catarinaseigward"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Kaiwen Lin :wave:"
  sub = "Welcome to my homepage."

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/homepage1.jpg' # header background image - default "/images/default_sidebar.jpg"
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo= '/images/s1mple.jpg' # - default "/images/23123123.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/CatarinaSeigward"
  linkedin = "www.linkedin.com/in/kaiwen-lin-aa8162284"
  instagram = "https://www.instagram.com/realkaiwenlin/"
  email = "mailto:dameilin66@gmail.com"
  steam = "https://steamcommunity.com/id/dameilin45/"

[params.contact]
  email = "dameilin66@gmail.com"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/post/"
  weight = -100

#[[menu.main]]
#name = "CV"
#url = "/resume/Kaiwen-Lin-CV.pdf"
#weight = 10

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.x]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true